/* Meraki by Saima — site behaviour.

   Product data enters through exactly one door: mapProduct(). Everything below
   the mapping layer renders the normalised shape and neither knows nor cares
   where a product came from — today /api/products, tomorrow the same endpoint
   backed by Supabase. Only the endpoint's data source changes. */

/* IMG-SRCSET:START — generated by tools/optimize-images.py, do not edit by hand */
var IMG_SRCSET = {
  'img/p1.webp': 'img/sm/p1.webp 560w, img/md/p1.webp 960w, img/p1.webp 1400w',
  'img/p2.webp': 'img/sm/p2.webp 560w, img/p2.webp 938w',
  'img/p3.webp': 'img/sm/p3.webp 560w, img/p3.webp 938w',
  'img/p4.webp': 'img/sm/p4.webp 560w, img/md/p4.webp 960w, img/p4.webp 1400w',
  'img/p5.webp': 'img/sm/p5.webp 560w, img/md/p5.webp 960w, img/p5.webp 1400w',
  'img/p6.webp': 'img/sm/p6.webp 560w, img/md/p6.webp 960w, img/p6.webp 1400w',
  'img/p7.webp': 'img/sm/p7.webp 560w, img/p7.webp 937w',
  'img/p8.webp': 'img/sm/p8.webp 560w, img/p8.webp 941w'
};
/* IMG-SRCSET:END */

/* ============================================================================
   MAPPING LAYER — the only place that understands the published contract
   ========================================================================== */

/* How each availability value presents to a customer.

   Availability is an inventory state and nothing more. It says whether a piece
   exists now or is cut to order; it cannot say how quickly Saima ships, so the
   website never derives a shipping time from it. A quantity is likewise never
   implied — the contract carries no stock counts. Which sizes exist is the only
   stock-shaped fact on the page, and that comes from `sizes`.

   A per-piece timing promise belongs to the app, in `fulfillment_note`. */
var AVAILABILITY = {
  ready_now:     { label: 'Ready now',                      dot: '#7A8B5A' },
  made_to_order: { label: 'Made to order',                  dot: '#A6802E' },
  both:          { label: 'Ready now · also made to order', dot: '#7A8B5A' }
};

var GARMENT_ROWS = [
  ['fabric', 'Fabric'],
  ['pieces', 'Pieces'],
  ['color',  'Colour'],   /* contract key is `color`; customers read "Colour" */
  ['made',   'Made'],
  ['care',   'Care']
];

/* A size list is offered so the visitor can still start a conversation about a
   piece whose sizes the app has not published. */
var CUSTOM_SIZE = 'Other / Custom';

function blank(v) { return v === null || v === undefined || String(v).trim() === ''; }

function formatPrice(value, currency) {
  if (blank(value)) return '';
  if (typeof value !== 'number') return String(value);   /* already formatted */
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency', currency: currency || 'USD',
      minimumFractionDigits: 0, maximumFractionDigits: value % 1 ? 2 : 0
    }).format(value);
  } catch (e) {
    return '$' + value;
  }
}

/* "img/sm/p1.webp 560w, img/p1.webp 1400w" from { 560: …, 1400: … }.

   Falls back to the generated IMG_SRCSET for the local fixture photography, so
   the renditions this repo already ships keep being used without duplicating
   the generator's output into the fixtures. A remote image carrying its own
   `variants` needs neither. An image with neither simply renders from `src`. */
function srcsetFrom(variants, src) {
  if (variants) {
    var widths = Object.keys(variants)
      .map(Number)
      .filter(function (w) { return w > 0 && !blank(variants[w]); })
      .sort(function (a, b) { return a - b; });
    if (widths.length) {
      return widths.map(function (w) { return variants[w] + ' ' + w + 'w'; }).join(', ');
    }
  }
  return IMG_SRCSET[src] || '';
}

/* Ordered by sort_order, with the primary photograph first. Every renderer
   treats images[0] as the hero, so hero selection is decided once, here. */
function mapImages(list, fallbackAlt) {
  var imgs = (list || [])
    .map(function (raw, i) {
      var img = (typeof raw === 'string') ? { src: raw } : (raw || {});
      return {
        src: img.src,
        alt: blank(img.alt) ? fallbackAlt : img.alt,
        role: img.role || null,
        width: img.width || null,
        height: img.height || null,
        isPrimary: img.is_primary === true,
        order: typeof img.sort_order === 'number' ? img.sort_order : i,
        srcset: srcsetFrom(img.variants, img.src)
      };
    })
    .filter(function (img) { return !blank(img.src); });

  imgs.sort(function (a, b) { return a.order - b.order; });

  for (var i = 0; i < imgs.length; i++) {
    if (imgs[i].isPrimary) { imgs.unshift(imgs.splice(i, 1)[0]); break; }
  }
  return imgs;
}

/* [label, value] pairs worth showing. A blank value is dropped rather than
   rendered as a labelled row with nothing beside it. */
function mapGarmentDetails(details) {
  var g = details || {};
  return GARMENT_ROWS
    .map(function (row) { return [row[1], g[row[0]]]; })
    .filter(function (row) { return !blank(row[1]); });
}

/* The single door product data comes through. Everything downstream renders
   this shape and never touches the raw payload. */
function mapProduct(raw) {
  if (!raw || blank(raw.id)) return null;
  var avail = AVAILABILITY[raw.availability] || AVAILABILITY.made_to_order;
  var sizes = (raw.sizes || []).filter(function (s) { return !blank(s); });

  return {
    id: raw.id,
    slug: blank(raw.slug) ? raw.id : raw.slug,
    sku: raw.sku || null,
    name: raw.name || '',
    description: raw.description || '',
    price: formatPrice(raw.price, raw.currency),
    priceValue: raw.price,
    collections: raw.collection_names || [],
    availability: raw.availability || 'made_to_order',
    availabilityLabel: avail.label,
    dot: avail.dot,
    /* Only ever what the app actually says about fulfilment. Absent means the
       line is not rendered at all — silence rather than a guess. */
    delivery: blank(raw.fulfillment_note) ? '' : String(raw.fulfillment_note).trim(),
    sizes: sizes.length ? sizes : [CUSTOM_SIZE],
    details: mapGarmentDetails(raw.garment_details),
    images: mapImages(raw.images, raw.name || ''),
    publishedAt: raw.published_at || null
  };
}

function mapProducts(list) {
  return (list || []).map(mapProduct).filter(Boolean);
}

/* Where the published catalogue is read from. Same origin, so no CORS, no
   credentials, no cookies. */
var PRODUCTS_ENDPOINT = '/api/products';

/* The normalised catalogue every renderer reads. Empty until the fetch below
   resolves; it is mutated in place rather than reassigned so nothing can end up
   holding a reference to a stale array. */
var PRODUCTS = [];

var state = { filter:'all', slug:null, size:null, shot:0, bag:[], sent:false };

/* Is the catalogue usable yet? 'loading' | 'ready' | 'error'.

   Nothing is known until /api/products answers, so the page starts in
   'loading' and every view renders its waiting state from the outset. */
var catalogue = { status: 'loading', error: null };

/* Deliberately holds no product data of its own: the catalogue lives in
   PRODUCTS and response caching belongs to the CDN, not to the page. */
function setCatalogueState(status, error) {
  catalogue.status = status;
  catalogue.error = error || null;
  renderGrids();
  renderBag();
  route();   /* re-resolve wherever the visitor already is, without a refresh */
}

var $ = function (s) { return document.querySelector(s); };
var byId = function (id) { return document.getElementById(id); };

/* Identity is the id — a UUID once live. Never used in a URL. */
function findProduct(id) {
  return PRODUCTS.filter(function (p) { return p.id === id; })[0] || null;
}

/* Routing is the slug — human, shareable, stable across renames. Both return
   null when unknown, including while the catalogue is still empty; callers
   must handle that rather than assume a product came back. */
function findProductBySlug(slug) {
  return PRODUCTS.filter(function (p) { return p.slug === slug; })[0] || null;
}

/* Bags saved before ids and slugs were separated stored the slug under `id`.
   Resolving by id first and slug second keeps those inquiries intact without
   rewriting anything in storage. */
function findBagProduct(id) {
  return findProduct(id) || findProductBySlug(id);
}

/* Escape anything that ends up inside an HTML string below, so an apostrophe or
   an ampersand in a product name can never break the markup. */
function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/* One image helper for every photograph on the site, local or remote. It takes
   a normalised image and emits srcset only when renditions actually exist, so
   a lone remote original still renders correctly from its src. */
function imgHTML(image, sizes, attrs) {
  if (!image || blank(image.src)) return '';
  return '<img src="' + esc(image.src) + '" alt="' + esc(image.alt) + '"' +
    (image.srcset ? ' srcset="' + esc(image.srcset) + '" sizes="' + esc(sizes) + '"' : '') +
    ' ' + (attrs || '') + '>';
}

/* ---------- cards ---------- */
var CARD_SIZES = '(max-width:640px) 92vw, (max-width:1100px) 44vw, 300px';

function cardHTML(p, small) {
  return '<a class="card" href="#/product/' + esc(p.slug) + '">' +
    '<div class="shot">' + imgHTML(p.images[0], CARD_SIZES, 'loading="lazy" decoding="async"') + '</div>' +
    '<div class="meta"><p class="name">' + esc(p.name) + '</p><p class="price">' + esc(p.price) + '</p>' +
    (small ? '' : '<p class="status"><span class="dot" style="background:' + esc(p.dot) + '"></span>' + esc(p.availabilityLabel) + '</p>') +
    '</div></a>';
}

/* 'both' belongs in both lists, so the filters test what a piece can be rather
   than sorting it into one bucket. */
function matchesFilter(p, filter) {
  if (filter === 'all') return true;
  if (filter === 'ready') return p.availability === 'ready_now' || p.availability === 'both';
  return p.availability === 'made_to_order' || p.availability === 'both';
}

/* Which piece the home hero photograph shows. The caption is read from the
   catalogue rather than written into the markup, so it cannot contradict the
   product page or outlive the piece. The photograph itself is still in
   index.html — see the comment there. */
var HERO_SLUG = 'mehr';

function renderHeroTag() {
  var tag = byId('hero-tag');
  if (!tag) return;
  var p = findProductBySlug(HERO_SLUG);
  tag.classList.toggle('hidden', !p);
  if (!p) return;
  byId('hero-name').textContent = p.name;
  byId('hero-status').textContent = p.availabilityLabel;
}

function renderGrids() {
  renderHeroTag();
  byId('featured-grid').innerHTML = PRODUCTS.slice(0, 4).map(function (p) { return cardHTML(p); }).join('');
  var shown = PRODUCTS.filter(function (p) { return matchesFilter(p, state.filter); });
  byId('collection-grid').innerHTML = shown.map(function (p) { return cardHTML(p); }).join('');
  byId('collection-count').textContent =
    catalogue.status === 'loading' ? 'Loading the collection…'
    : catalogue.status === 'error' ? 'We couldn’t load the collection. Please try again.'
    : shown.length + ' pieces · sizes 38–46 and custom';
  Array.prototype.forEach.call(byId('filters').children, function (b) {
    b.setAttribute('aria-pressed', String(b.dataset.filter === state.filter));
  });
}

/* ---------- product ---------- */
function renderProduct() {
  var p = findProductBySlug(state.slug);

  /* The product may be unknown because the catalogue has not arrived yet, or
     because it genuinely is not there. Those read very differently to a
     visitor, so say which — and never fall through into the render below with
     nothing to render. */
  var stateEl = byId('pdp-state');
  var pdp = $('#view-product .pdp');
  var also = $('#view-product .also');
  if (!p) {
    stateEl.textContent =
      catalogue.status === 'ready' ? 'We couldn’t find that piece.'
      : catalogue.status === 'error' ? 'We couldn’t load this piece. Please try again.'
      : 'Loading…';
    stateEl.classList.remove('hidden');
    pdp.classList.add('hidden');
    also.classList.add('hidden');
    return;
  }
  stateEl.classList.add('hidden');
  pdp.classList.remove('hidden');
  also.classList.remove('hidden');

  var others = PRODUCTS.filter(function (x) { return x.id !== p.id; });
  var shots = p.images;
  if (state.shot >= shots.length) state.shot = 0;

  var hero = byId('pdp-hero');
  var shot = shots[state.shot];
  hero.src = shot.src;
  hero.alt = shot.alt;
  if (shot.srcset) { hero.srcset = shot.srcset; hero.sizes = '(max-width:900px) 100vw, 46vw'; }
  else { hero.removeAttribute('srcset'); hero.removeAttribute('sizes'); }

  /* One photograph needs no thumbnail strip. Hiding the container rather than
     just emptying it also removes the gallery's 14px flex gap, which an empty
     strip would otherwise leave under the main image. */
  var thumbs = byId('pdp-thumbs');
  thumbs.classList.toggle('hidden', shots.length < 2);
  thumbs.innerHTML = shots.length < 2 ? '' : shots.map(function (s, i) {
    return '<button data-shot="' + i + '" aria-pressed="' + (state.shot === i) + '" aria-label="View ' + (i + 1) + '">' +
      imgHTML(s, '(max-width:900px) 24vw, 130px',
        'loading="lazy" decoding="async" style="object-position:' + (i === 0 ? '50% 15%' : '50% 30%') + '"') +
      '</button>';
  }).join('');

  byId('pdp-name').textContent = p.name;
  byId('pdp-price').textContent = p.price;
  byId('pdp-status').textContent = p.availabilityLabel;
  byId('pdp-dot').style.background = p.dot;
  byId('pdp-desc').textContent = p.description;

  /* No fulfilment note published means no line — an empty <p> would still take
     its place in the flex column and leave a gap under the button. */
  var deliveryEl = byId('pdp-delivery');
  deliveryEl.textContent = p.delivery;
  deliveryEl.classList.toggle('hidden', blank(p.delivery));

  byId('pdp-sizes').innerHTML = p.sizes.map(function (s) {
    return '<button data-size="' + esc(s) + '" aria-pressed="' + (state.size === s) + '">' + esc(s) + '</button>';
  }).join('');

  /* Hiding the block when nothing survives also removes its top rule, which
     would otherwise sit under the delivery note as an unexplained hairline. */
  var specsEl = byId('pdp-specs');
  specsEl.classList.toggle('hidden', p.details.length === 0);
  specsEl.innerHTML = p.details.map(function (r) {
    return '<div><p class="k">' + esc(r[0]) + '</p><p class="v">' + esc(r[1]) + '</p></div>';
  }).join('');

  var inBag = state.bag.some(function (b) { return b.id === p.id; });
  var add = byId('pdp-add');
  add.dataset.state = inBag ? 'added' : (state.size ? 'ready' : 'idle');
  add.textContent = inBag ? 'In your inquiry ✓' : (state.size ? 'Add to inquiry' : 'Select a size');
  add.disabled = inBag;

  byId('pdp-related').innerHTML = others.slice(0, 4).map(function (x) { return cardHTML(x, true); }).join('');
}

/* ---------- inquiry ---------- */
var BAG_KEY = 'meraki.inquiry.v1';

function saveBag() {
  try { localStorage.setItem(BAG_KEY, JSON.stringify(state.bag)); } catch (e) { /* private mode */ }
}

/* Only the product id and the chosen size are persisted — never a copy of the
   product. Everything a row displays is read from the catalogue at render
   time, so a saved inquiry can never show a stale name, price or photograph.

   Loading deliberately does NOT check ids against PRODUCTS. It used to, which
   meant that if the catalogue were ever momentarily empty — precisely what
   happens while an async fetch is in flight — every entry looked unknown, the
   bag was emptied, and the next save wrote that empty bag over the customer's
   inquiry. Persistence and validation are separate concerns: an entry is kept
   until the visitor removes it. */
function loadBag() {
  try {
    var raw = localStorage.getItem(BAG_KEY);
    var saved = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(saved)) return;
    state.bag = saved
      .filter(function (b) { return b && b.id; })
      .map(function (b) { return { id: b.id, size: b.size }; });
  } catch (e) { state.bag = []; }
}

/* A saved entry whose product is not in the catalogue is still shown and still
   removable — it is never dropped on the visitor's behalf. Which message it
   carries depends on whether the catalogue has finished loading. */
function bagRowHTML(b, i) {
  var p = findBagProduct(b.id);
  var name = p ? p.name
    : catalogue.status === 'ready' ? 'No longer available'
    : catalogue.status === 'error' ? 'Couldn’t load this piece'
    : 'Loading…';
  var line = (p ? esc(p.price) + ' · ' : '') + 'Size ' + esc(b.size);
  return '<div class="bagrow"><div class="thumb">' +
    (p ? imgHTML(p.images[0], '92px', 'loading="lazy" decoding="async"') : '') + '</div>' +
    '<div class="info"><p class="name">' + esc(name) + '</p>' +
    '<p class="price">' + line + '</p>' +
    '<p class="status" style="margin-top:2px">' + esc(p ? p.availabilityLabel : '') + '</p></div>' +
    '<button class="remove" data-remove="' + i + '" aria-label="Remove ' + esc(name) + ' from your inquiry">Remove</button></div>';
}

function renderBag() {
  byId('bag-count').textContent = String(state.bag.length);
  var n = state.bag.length;
  byId('bag-label').textContent = n === 0 ? 'Nothing selected yet'
    : n + (n === 1 ? ' look selected' : ' looks selected');

  byId('bag-list').innerHTML = n === 0
    ? '<div class="empty"><p class="body">You haven\'t selected any looks yet.</p>' +
      '<button class="pill pill-ghost" style="padding:14px 28px" data-nav="#/collection">Browse the collection</button></div>'
    : state.bag.map(function (b, i) { return bagRowHTML(b, i); }).join('');

  var submit = byId('inq-submit');
  submit.dataset.ready = String(n > 0);
  submit.disabled = n === 0;
}

/* Everything the atelier needs to answer an inquiry. Kept in one place so that
   whatever we point it at later — Supabase, WhatsApp, email — reads the same
   shape. The id identifies the piece; the slug is included only so a human
   reading the record can find the page. See the README. */
function inquiryPayload(form) {
  return {
    submittedAt: new Date().toISOString(),
    name: form.name.value.trim(),
    phone: form.phone.value.trim(),
    email: form.email.value.trim(),
    note: form.note.value.trim(),
    items: state.bag.map(function (b) {
      var p = findBagProduct(b.id);
      return {
        id: p ? p.id : b.id,
        slug: p ? p.slug : null,
        sku: p ? p.sku : null,
        name: p ? p.name : null,
        size: b.size,
        price: p ? p.price : null
      };
    })
  };
}

/* ---------- routing ---------- */
var VIEWS = ['home', 'collection', 'product', 'inquiry'];

function show(view) {
  VIEWS.forEach(function (v) { byId('view-' + v).classList.toggle('hidden', v !== view); });
}

function route() {
  var hash = location.hash.replace(/^#\/?/, '');

  /* Leaving the inquiry page retires the thank-you screen, so the next visit
     starts a fresh inquiry rather than showing the old confirmation forever. */
  if (hash !== 'inquiry') state.sent = false;

  if (hash.indexOf('product/') === 0) {
    state.slug = decodeURIComponent(hash.slice(8));
    state.size = null; state.shot = 0;
    renderProduct(); show('product'); window.scrollTo(0, 0); return;
  }
  if (hash === 'collection' || hash === 'ready' || hash === 'made-to-order') {
    state.filter = hash === 'ready' ? 'ready' : (hash === 'made-to-order' ? 'mto' : 'all');
    renderGrids(); show('collection'); window.scrollTo(0, 0); return;
  }
  if (hash === 'inquiry') {
    byId('inq-form-wrap').classList.toggle('hidden', state.sent);
    byId('inq-thanks').classList.toggle('hidden', !state.sent);
    renderBag(); show('inquiry'); window.scrollTo(0, 0); return;
  }

  show('home');
  if (hash === 'story') {
    var el = byId('story');
    if (el) window.scrollTo({ top: el.offsetTop - 90, behavior: 'smooth' });
  } else {
    window.scrollTo(0, 0);
  }
}

/* ---------- events (delegated) ---------- */
document.addEventListener('click', function (e) {
  if (!e.target || !e.target.closest) return;

  var nav = e.target.closest('[data-nav]');
  if (nav) { location.hash = nav.dataset.nav; return; }

  var shot = e.target.closest('[data-shot]');
  if (shot) { state.shot = Number(shot.dataset.shot); renderProduct(); return; }

  var size = e.target.closest('[data-size]');
  if (size) { state.size = size.dataset.size; renderProduct(); return; }

  var filt = e.target.closest('[data-filter]');
  if (filt) { state.filter = filt.dataset.filter; renderGrids(); return; }

  var rm = e.target.closest('[data-remove]');
  if (rm) { state.bag.splice(Number(rm.dataset.remove), 1); saveBag(); renderBag(); return; }

  if (e.target.closest('#pdp-add')) {
    var p = findProductBySlug(state.slug);
    if (!p || !state.size || state.bag.some(function (b) { return b.id === p.id; })) return;
    state.bag.push({ id: p.id, size: state.size });   /* identity is the id, never the slug */
    saveBag(); renderProduct(); renderBag();
  }
});

byId('inquiry-form').addEventListener('submit', function (e) {
  e.preventDefault();
  if (!state.bag.length) return;

  var payload = inquiryPayload(e.target);

  /* Nothing is sent anywhere yet. This is the single seam to wire up later —
     the thank-you screen below is already the success state. */
  if (window.console && console.info) console.info('Inquiry (not yet sent anywhere):', payload);

  state.sent = true;
  state.bag = [];
  saveBag();
  e.target.reset();
  renderBag();
  route();
});

/* Fetch the published catalogue and hand every product through the same
   mapProduct() the fixtures went through. There is deliberately no embedded
   fallback catalogue: if this fails the storefront says so, rather than
   quietly serving a copy of the products baked in at deploy time. */
function loadCatalogue() {
  setCatalogueState('loading');

  return fetch(PRODUCTS_ENDPOINT, { headers: { Accept: 'application/json' } })
    .then(function (res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.json();
    })
    .then(function (payload) {
      var mapped = mapProducts(payload && payload.products);
      PRODUCTS.length = 0;
      PRODUCTS.push.apply(PRODUCTS, mapped);
      setCatalogueState('ready');
    })
    .catch(function (err) {
      PRODUCTS.length = 0;
      setCatalogueState('error', err);
    });
}

window.addEventListener('hashchange', route);
loadBag();
loadCatalogue();
