/* Meraki by Saima — site behaviour.

   Product data enters through exactly one door: mapProduct(). Everything below
   the mapping layer renders the normalised shape and neither knows nor cares
   where a product came from — today /api/products, tomorrow the same endpoint
   backed by Supabase. Only the endpoint's data source changes. */

/* IMG-SRCSET:START — generated by tools/optimize-images.py, do not edit by hand */
var IMG_SRCSET = {
  'img/p1.webp': 'img/sm/p1.webp 560w, img/md/p1.webp 960w, img/p1.webp 1400w',
  'img/p2.webp': 'img/sm/p2.webp 560w, img/p2.webp 938w',
  'img/p3.webp': 'img/sm/p3.webp 560w, img/p3.webp 938w',
  'img/p4.webp': 'img/sm/p4.webp 560w, img/md/p4.webp 960w, img/p4.webp 1400w',
  'img/p5.webp': 'img/sm/p5.webp 560w, img/md/p5.webp 960w, img/p5.webp 1400w',
  'img/p6.webp': 'img/sm/p6.webp 560w, img/md/p6.webp 960w, img/p6.webp 1400w',
  'img/p7.webp': 'img/sm/p7.webp 560w, img/p7.webp 937w',
  'img/p8.webp': 'img/sm/p8.webp 560w, img/p8.webp 941w'
};
/* IMG-SRCSET:END */

/* ============================================================================
   MAPPING LAYER — the only place that understands the published contract
   ========================================================================== */

/* How each availability value presents to a customer.

   Availability is an inventory state and nothing more. It says whether a piece
   exists now or is cut to order; it cannot say how quickly Saima ships, so the
   website never derives a shipping time from it. A quantity is likewise never
   implied — the contract carries no stock counts. Which sizes exist is the only
   stock-shaped fact on the page, and that comes from `sizes`.

   A per-piece timing promise belongs to the app, in `fulfillment_note`. */
var AVAILABILITY = {
  ready_now:     { label: 'Ready now',                      dot: '#7A8B5A' },
  made_to_order: { label: 'Made to order',                  dot: '#A6802E' },
  both:          { label: 'Ready now · also made to order', dot: '#7A8B5A' }
};

var GARMENT_ROWS = [
  ['fabric', 'Fabric'],
  ['pieces', 'Pieces'],
  ['color',  'Colour'],   /* contract key is `color`; customers read "Colour" */
  ['made',   'Made'],
  ['care',   'Care']
];

/* TEMPORARY, for launch. The catalogue carries sizing from several eras — some
   pieces list S/M, some list 38–46, some list nothing — so offering a size
   would mean offering a different vocabulary depending on which piece a
   customer happened to open. Until Ready Now and Made to Order have a sizing
   model of their own, size is settled in the follow-up conversation instead.
 *
 * Presentation only, and deliberately one switch. /api/products keeps
 * returning `sizes`, mapProduct keeps mapping them, and no stored data is
 * touched — so re-enabling this is this line, with nothing to migrate.
 *
 * Everything that reads it: the PDP size block, the Add to Inquiry button's
 * requirements, and the places the global size note is shown (a "sizes 38–46"
 * claim is confusing next to a page that offers no sizes). */
var SHOW_SIZE_SELECTION = false;

/* Never shown to a customer. The app keeps a custom option for its own use, but
   the storefront offers only sizes that actually exist — someone needing custom
   sizing says so in the inquiry note. */
var HIDDEN_SIZE_LABELS = ['other / custom', 'other', 'custom'];

function isPublicSize(label) {
  return !blank(label) && HIDDEN_SIZE_LABELS.indexOf(String(label).trim().toLowerCase()) === -1;
}

function blank(v) { return v === null || v === undefined || String(v).trim() === ''; }

function formatPrice(value, currency) {
  if (blank(value)) return '';
  if (typeof value !== 'number') return String(value);   /* already formatted */
  try {
    return new Intl.NumberFormat('en-US', {
      style: 'currency', currency: currency || 'USD',
      minimumFractionDigits: 0, maximumFractionDigits: value % 1 ? 2 : 0
    }).format(value);
  } catch (e) {
    return '$' + value;
  }
}

/* srcset has its own grammar: candidates are comma-separated and, inside a
   candidate, whitespace separates the URL from its descriptor. A URL carrying
   either character therefore cannot be written literally — it has to be
   percent-encoded, or the candidate list is misparsed.

   Only literal spaces and commas are touched, so a URL that already arrives
   percent-encoded is left exactly as it is rather than double-encoded. */
function srcsetSafeUrl(url) {
  return String(url).replace(/\s/g, '%20').replace(/,/g, '%2C');
}

/* The real pixel width of a rendition.

   The app keys its renditions by the LONGEST SIDE it targeted, not by the
   width of the file it produced. For a portrait photograph those are very
   different things: the "1400" rendition of a 937x1679 master is 781x1400, not
   1400 wide. Emitting `… 1400w` for a 781px file tells the browser it is
   getting nearly twice the detail it actually gets, and the browser then
   settles for a file far too small for the slot.

   A `w` descriptor must state the file's real width, so it is derived here
   from the master's aspect ratio. The clamp is what makes the derivation safe:
   the app never upscales, so no rendition can be wider than its master. If the
   longest-side reading is ever wrong for some image, this understates rather
   than overstates — and understating makes a browser pick a LARGER file, which
   costs bytes rather than sharpness. */
function variantWidth(key, masterW, masterH) {
  if (!(masterW > 0) || !(masterH > 0) || !(key > 0)) return null;
  var w = masterH > masterW ? Math.round(key * masterW / masterH) : key;
  return Math.max(1, Math.min(w, masterW));
}

/* "…/560.webp 313w, …/960.webp 536w, …/master.webp 937w".
 *
 * The master is included as a candidate on purpose. Once a srcset exists the
 * browser chooses only from it, so without the master the widest thing on
 * offer for Steel Grey would be 781px — narrower than a desktop gallery needs,
 * and guaranteed to look soft no matter how honest the other descriptors are.
 *
 * Descriptors can only be derived when the master's dimensions are known. If
 * they are not, no srcset is emitted at all and `src` — the master — serves.
 * Heavier, but never a lie about how much detail a file holds.
 *
 * Falls back to the generated IMG_SRCSET for the local editorial photography,
 * whose renditions really are keyed by width. */
function srcsetFrom(variants, src, masterW, masterH) {
  if (variants) {
    var keys = Object.keys(variants)
      .map(Number)
      .filter(function (k) { return k > 0 && !blank(variants[k]); })
      .sort(function (a, b) { return a - b; });

    if (keys.length) {
      var parts = [];
      var seenWidth = {};
      var seenUrl = {};
      var add = function (url, width) {
        /* Two candidates sharing a width is invalid srcset; after clamping to
           the master, small masters can collapse several keys onto one. And a
           rendition whose URL is simply the master — which happens when the
           app had nothing to downscale — must not be offered twice at two
           different widths, since only one of them can be true. */
        if (!width || blank(url) || seenWidth[width]) return;
        var safe = srcsetSafeUrl(url);
        if (seenUrl[safe]) return;
        seenWidth[width] = true;
        seenUrl[safe] = true;
        parts.push(safe + ' ' + width + 'w');
      };

      /* The master goes in first because its width is known outright rather
         than derived, so if a rendition turns out to be the master under
         another name the authoritative number is the one that survives. */
      add(src, masterW > 0 ? Math.round(masterW) : null);
      keys.forEach(function (k) { add(variants[k], variantWidth(k, masterW, masterH)); });

      /* Ascending by width: the browser does not care, but a human reading
         View Source does. */
      parts.sort(function (a, b) {
        return parseInt(a.split(' ').pop(), 10) - parseInt(b.split(' ').pop(), 10);
      });
      if (parts.length > 1) return parts.join(', ');
      return '';   /* nothing to choose between: let src serve */
    }
  }
  return IMG_SRCSET[src] || '';
}

/* Ordered by sort_order, with the primary photograph first. Every renderer
   treats images[0] as the hero, so hero selection is decided once, here. */
function mapImages(list, fallbackAlt) {
  var imgs = (list || [])
    .map(function (raw, i) {
      var img = (typeof raw === 'string') ? { src: raw } : (raw || {});
      return {
        src: img.src,
        alt: blank(img.alt) ? fallbackAlt : img.alt,
        role: img.role || null,
        width: img.width || null,
        height: img.height || null,
        isPrimary: img.is_primary === true,
        order: typeof img.sort_order === 'number' ? img.sort_order : i,
        srcset: srcsetFrom(img.variants, img.src, img.width, img.height)
      };
    })
    .filter(function (img) { return !blank(img.src); });

  imgs.sort(function (a, b) { return a.order - b.order; });

  for (var i = 0; i < imgs.length; i++) {
    if (imgs[i].isPrimary) { imgs.unshift(imgs.splice(i, 1)[0]); break; }
  }
  return imgs;
}

/* [label, value] pairs worth showing. A blank value is dropped rather than
   rendered as a labelled row with nothing beside it. */
function mapGarmentDetails(details) {
  var g = details || {};
  return GARMENT_ROWS
    .map(function (row) { return [row[1], g[row[0]]]; })
    .filter(function (row) { return !blank(row[1]); });
}

/* The single door product data comes through. Everything downstream renders
   this shape and never touches the raw payload. */
function mapProduct(raw) {
  if (!raw || blank(raw.id)) return null;
  var avail = AVAILABILITY[raw.availability] || AVAILABILITY.made_to_order;
  var sizes = (raw.sizes || []).filter(isPublicSize);

  return {
    id: raw.id,
    slug: blank(raw.slug) ? raw.id : raw.slug,
    sku: raw.sku || null,
    name: raw.name || '',
    description: raw.description || '',
    price: formatPrice(raw.price, raw.currency),
    priceValue: raw.price,
    collections: raw.collection_names || [],
    availability: raw.availability || 'made_to_order',
    availabilityLabel: avail.label,
    dot: avail.dot,
    /* The piece's own note, exactly as the app stores it. Kept raw: what the
       page actually shows is resolved at render time by
       getEffectiveFulfillment(), because it may depend on a global setting
       that arrives separately. Nothing is ever written back. */
    fulfillmentNote: blank(raw.fulfillment_note) ? '' : String(raw.fulfillment_note).trim(),
    /* May legitimately be empty: the size selector then hides itself and the
       piece can still be added to an inquiry without one. */
    sizes: sizes,
    details: mapGarmentDetails(raw.garment_details),
    images: mapImages(raw.images, raw.name || ''),
    publishedAt: raw.published_at || null
  };
}

function mapProducts(list) {
  return (list || []).map(mapProduct).filter(Boolean);
}

/* What the page should say about timing for one piece, right now.
 *
 * Two sources, and the piece's own note always wins:
 *
 *   ready_now      note → the note;  blank → nothing. The global made-to-order
 *                  lead time is a promise about making a piece, and a piece
 *                  that already exists is not being made. It must not apply.
 *   made_to_order  note → the note;  blank → the global lead time
 *   both           note → the note;  blank → the global lead time
 *
 * Blank on both sides means no line at all, never an empty one.
 *
 * Presentation only. The global value is read each time it is needed rather
 * than copied into the product, so changing the lead time in the app changes
 * every piece that relies on it, with nothing to migrate and nothing to go
 * stale. It is deliberately not part of the API contract.
 */
function getEffectiveFulfillment(product, settings) {
  if (!product) return '';
  if (!blank(product.fulfillmentNote)) return String(product.fulfillmentNote).trim();
  /* Only ready_now is excluded, so an unrecognised availability falls back the
     same way mapProduct's label does — made to order. */
  if (product.availability === 'ready_now') return '';
  var lead = settings && settings.made_to_order_lead_time;
  return blank(lead) ? '' : String(lead).trim();
}

/* Where the published catalogue and the operational settings are read from.
   Same origin, so no CORS, no credentials, no cookies. */
var PRODUCTS_ENDPOINT = '/api/products';
var SETTINGS_ENDPOINT = '/api/site-settings';

/* Everything Saima maintains in the app. Blank until the fetch resolves, and
   blank again if it fails — every consumer hides the line it cannot fill, so a
   settings outage costs a few footer lines rather than the whole storefront. */
function blankSettings() {
  return {
    featured_product_id: null, whatsapp: null, contact_email: null,
    instagram_url: null, location: null, made_to_order_lead_time: null,
    size_service_note: null, inquiry_response_note: null
  };
}
var SETTINGS = blankSettings();

/* The normalised catalogue every renderer reads. Empty until the fetch below
   resolves; it is mutated in place rather than reassigned so nothing can end up
   holding a reference to a stale array. */
var PRODUCTS = [];

var state = { filter:'all', slug:null, size:null, shot:0, bag:[], sent:false };

/* Is the catalogue usable yet? 'loading' | 'ready' | 'error'.

   Nothing is known until /api/products answers, so the page starts in
   'loading' and every view renders its waiting state from the outset. */
var catalogue = { status: 'loading', error: null };

/* Deliberately holds no product data of its own: the catalogue lives in
   PRODUCTS and response caching belongs to the CDN, not to the page. */
function setCatalogueState(status, error) {
  catalogue.status = status;
  catalogue.error = error || null;
  renderGrids();
  renderBag();
  route();   /* re-resolve wherever the visitor already is, without a refresh */
}

var $ = function (s) { return document.querySelector(s); };
var byId = function (id) { return document.getElementById(id); };

/* Identity is the id — a UUID once live. Never used in a URL. */
function findProduct(id) {
  return PRODUCTS.filter(function (p) { return p.id === id; })[0] || null;
}

/* Routing is the slug — human, shareable, stable across renames. Both return
   null when unknown, including while the catalogue is still empty; callers
   must handle that rather than assume a product came back. */
function findProductBySlug(slug) {
  return PRODUCTS.filter(function (p) { return p.slug === slug; })[0] || null;
}

/* Bags saved before ids and slugs were separated stored the slug under `id`.
   Resolving by id first and slug second keeps those inquiries intact without
   rewriting anything in storage. */
function findBagProduct(id) {
  return findProduct(id) || findProductBySlug(id);
}

/* Escape anything that ends up inside an HTML string below, so an apostrophe or
   an ampersand in a product name can never break the markup. */
function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/* One image helper for every photograph on the site, local or remote. It takes
   a normalised image and emits srcset only when renditions actually exist, so
   a lone remote original still renders correctly from its src. */
function imgHTML(image, sizes, attrs) {
  if (!image || blank(image.src)) return '';
  return '<img src="' + esc(image.src) + '" alt="' + esc(image.alt) + '"' +
    (image.srcset ? ' srcset="' + esc(image.srcset) + '" sizes="' + esc(sizes) + '"' : '') +
    ' ' + (attrs || '') + '>';
}

/* ---------- cards ---------- */
var CARD_SIZES = '(max-width:640px) 92vw, (max-width:1100px) 44vw, 300px';

function cardHTML(p, small) {
  return '<a class="card" href="#/product/' + esc(p.slug) + '">' +
    '<div class="shot">' + imgHTML(p.images[0], CARD_SIZES, 'loading="lazy" decoding="async"') + '</div>' +
    '<div class="meta"><p class="name">' + esc(p.name) + '</p><p class="price">' + esc(p.price) + '</p>' +
    (small ? '' : '<p class="status"><span class="dot" style="background:' + esc(p.dot) + '"></span>' + esc(p.availabilityLabel) + '</p>') +
    '</div></a>';
}

/* 'both' belongs in both lists, so the filters test what a piece can be rather
   than sorting it into one bucket. */
function matchesFilter(p, filter) {
  if (filter === 'all') return true;
  if (filter === 'ready') return p.availability === 'ready_now' || p.availability === 'both';
  return p.availability === 'made_to_order' || p.availability === 'both';
}

/* Which piece the home hero shows is Saima's choice, made in the app and read
   from Website Settings as a product id. It is resolved against the published
   catalogue, which is already filtered to published and unarchived — so a
   featured piece that is retired, archived or unpublished simply stops
   resolving, and the hero goes back to being a photograph with no caption.
   There is deliberately no fallback piece: naming a garment Saima did not
   choose is worse than naming none. */
function featuredProduct() {
  return blank(SETTINGS.featured_product_id) ? null : findProduct(SETTINGS.featured_product_id);
}

/* The editorial photograph exactly as index.html shipped it, captured before
   anything can overwrite it so the hero can always be put back. Without this
   the swap is one-way: once a product photograph is in place, a later render
   that has no product to show leaves the wrong garment on screen. */
var HERO_EDITORIAL = null;

function heroImg() { return $('.hero-img img'); }

function captureHeroEditorial() {
  var img = heroImg();
  if (!img || HERO_EDITORIAL) return;
  HERO_EDITORIAL = {
    src: img.getAttribute('src'), srcset: img.getAttribute('srcset'),
    sizes: img.getAttribute('sizes'), alt: img.getAttribute('alt')
  };
}

function setHeroImage(shot) {
  var img = heroImg();
  if (!img || !shot || blank(shot.src)) return;
  if (img.getAttribute('src') === shot.src) return;   /* already right; don't refetch */
  img.src = shot.src;
  img.alt = shot.alt || '';
  if (shot.srcset) { img.srcset = shot.srcset; img.sizes = shot.sizes || '(max-width:940px) 100vw, 53vw'; }
  else { img.removeAttribute('srcset'); img.removeAttribute('sizes'); }
}

/* The caption and the photograph move together or not at all.
 *
 * Three things could otherwise disagree — the caption, the photograph and the
 * alt text — and any two of them naming different garments is worse than
 * showing no caption. So there are exactly two safe states:
 *
 *   a featured piece that resolves AND has a photograph → its caption, its
 *   photograph, its alt
 *
 *   anything else → the editorial photograph with its own alt, no caption
 *
 * A featured piece with no usable image is not a partial success; it falls
 * back completely. */
function renderHero() {
  var tag = byId('hero-tag');
  if (!tag) return;
  captureHeroEditorial();

  var p = featuredProduct();
  var shot = (p && p.images.length && !blank(p.images[0].src)) ? p.images[0] : null;
  var safe = !!(p && shot);

  tag.classList.toggle('hidden', !safe);

  if (!safe) {
    byId('hero-name').textContent = '';
    byId('hero-status').textContent = '';
    setHeroImage(HERO_EDITORIAL);
    return;
  }

  byId('hero-name').textContent = p.name;
  byId('hero-status').textContent = p.availabilityLabel;
  setHeroImage(shot);
}

/* Whether the global size note may be shown to a customer at all. It reads
   "sizes 38–46 and custom" — a promise the storefront cannot currently let
   anyone act on, so while size selection is hidden the note is hidden with it
   everywhere rather than reworded into something new. The setting itself is
   untouched and comes straight back when sizing returns. */
function sizeServiceNote() {
  return SHOW_SIZE_SELECTION ? SETTINGS.size_service_note : null;
}

/* "12 pieces · sizes 38–46 and custom". The size clause is Saima's, from
   Website Settings — the range the atelier actually offers changes, and a
   number written into the page here would go on claiming the old one. No note
   set means no clause. */
function collectionCount(n) {
  var note = sizeServiceNote();
  return n + (n === 1 ? ' piece' : ' pieces') + (blank(note) ? '' : ' · ' + note);
}

function renderGrids() {
  renderHero();
  byId('featured-grid').innerHTML = PRODUCTS.slice(0, 4).map(function (p) { return cardHTML(p); }).join('');
  var shown = PRODUCTS.filter(function (p) { return matchesFilter(p, state.filter); });
  byId('collection-grid').innerHTML = shown.map(function (p) { return cardHTML(p); }).join('');
  byId('collection-count').textContent =
    catalogue.status === 'loading' ? 'Loading the collection…'
    : catalogue.status === 'error' ? 'We couldn’t load the collection. Please try again.'
    : collectionCount(shown.length);
  Array.prototype.forEach.call(byId('filters').children, function (b) {
    b.setAttribute('aria-pressed', String(b.dataset.filter === state.filter));
  });
}

/* ---------- product ---------- */
function renderProduct() {
  var p = findProductBySlug(state.slug);

  /* The product may be unknown because the catalogue has not arrived yet, or
     because it genuinely is not there. Those read very differently to a
     visitor, so say which — and never fall through into the render below with
     nothing to render. */
  var stateEl = byId('pdp-state');
  var pdp = $('#view-product .pdp');
  var also = $('#view-product .also');
  if (!p) {
    stateEl.textContent =
      catalogue.status === 'ready' ? 'We couldn’t find that piece.'
      : catalogue.status === 'error' ? 'We couldn’t load this piece. Please try again.'
      : 'Loading…';
    stateEl.classList.remove('hidden');
    pdp.classList.add('hidden');
    also.classList.add('hidden');
    return;
  }
  stateEl.classList.add('hidden');
  pdp.classList.remove('hidden');
  also.classList.remove('hidden');

  var others = PRODUCTS.filter(function (x) { return x.id !== p.id; });
  var shots = p.images;
  if (state.shot >= shots.length) state.shot = 0;

  var hero = byId('pdp-hero');
  var shot = shots[state.shot];
  hero.src = shot.src;
  hero.alt = shot.alt;
  hero.setAttribute('aria-label', 'View ' + (p.name || 'this piece') + ' larger');
  if (shot.srcset) { hero.srcset = shot.srcset; hero.sizes = '(max-width:900px) 100vw, 46vw'; }
  else { hero.removeAttribute('srcset'); hero.removeAttribute('sizes'); }

  /* One photograph needs no thumbnail strip. Hiding the container rather than
     just emptying it also removes the gallery's 14px flex gap, which an empty
     strip would otherwise leave under the main image. */
  var thumbs = byId('pdp-thumbs');
  thumbs.classList.toggle('hidden', shots.length < 2);
  thumbs.innerHTML = shots.length < 2 ? '' : shots.map(function (s, i) {
    return '<button data-shot="' + i + '" aria-pressed="' + (state.shot === i) + '" aria-label="View ' + (i + 1) + '">' +
      imgHTML(s, '(max-width:900px) 24vw, 130px',
        'loading="lazy" decoding="async" style="object-position:' + (i === 0 ? '50% 15%' : '50% 30%') + '"') +
      '</button>';
  }).join('');

  byId('pdp-name').textContent = p.name;
  byId('pdp-price').textContent = p.price;
  byId('pdp-status').textContent = p.availabilityLabel;
  byId('pdp-dot').style.background = p.dot;
  byId('pdp-desc').textContent = p.description;

  /* Nothing to say about timing means no line — an empty <p> would still take
     its place in the flex column and leave a gap under the button. The helper
     returns '' rather than null or undefined, so nothing can reach the page as
     the word "undefined". */
  var deliveryEl = byId('pdp-delivery');
  var delivery = getEffectiveFulfillment(p, SETTINGS);
  deliveryEl.textContent = delivery;
  deliveryEl.classList.toggle('hidden', blank(delivery));

  /* A piece with no published sizes shows no size control at all. Not an empty
     row, and emphatically not a fabricated "Custom" button — the app decides
     which sizes exist, and none is a legitimate answer. Such a piece can still
     be added to an inquiry; sizing is then settled in the conversation.

     While SHOW_SIZE_SELECTION is off the same is true of every piece: the
     block goes, heading and note with it, and nothing takes its place. The
     page runs from the description straight to Add to Inquiry. */
  var offerSizes = SHOW_SIZE_SELECTION && p.sizes.length > 0;
  byId('pdp-size-block').classList.toggle('hidden', !offerSizes);
  byId('pdp-sizes').innerHTML = !offerSizes ? '' : p.sizes.map(function (s) {
    return '<button data-size="' + esc(s) + '" aria-pressed="' + (state.size === s) + '">' + esc(s) + '</button>';
  }).join('');

  /* Hiding the block when nothing survives also removes its top rule, which
     would otherwise sit under the delivery note as an unexplained hairline. */
  var specsEl = byId('pdp-specs');
  specsEl.classList.toggle('hidden', p.details.length === 0);
  specsEl.innerHTML = p.details.map(function (r) {
    return '<div><p class="k">' + esc(r[0]) + '</p><p class="v">' + esc(r[1]) + '</p></div>';
  }).join('');

  /* "Select a size" is only an instruction when a size is actually on offer. */
  var ready = !offerSizes || state.size !== null;
  var inBag = state.bag.some(function (b) { return b.id === p.id; });
  var add = byId('pdp-add');
  add.dataset.state = inBag ? 'added' : (ready ? 'ready' : 'idle');
  add.textContent = inBag ? 'In your inquiry ✓' : (ready ? 'Add to inquiry' : 'Select a size');
  add.disabled = inBag;

  /* With nothing to suggest, the heading and the See More below it would be a
     section about nothing, so the whole block goes. */
  also.classList.toggle('hidden', others.length === 0);
  byId('pdp-related').innerHTML = others.slice(0, 4).map(function (x) { return cardHTML(x, true); }).join('');
}

/* ---------- inquiry ---------- */
var BAG_KEY = 'meraki.inquiry.v1';

/* True while a submission is in flight. Read by renderBag so the button cannot
   be re-enabled underneath a request that is still running. */
var submitting = false;

function saveBag() {
  try { localStorage.setItem(BAG_KEY, JSON.stringify(state.bag)); } catch (e) { /* private mode */ }
}

/* Only the product id and the chosen size are persisted — never a copy of the
   product. Everything a row displays is read from the catalogue at render
   time, so a saved inquiry can never show a stale name, price or photograph.

   Loading deliberately does NOT check ids against PRODUCTS. It used to, which
   meant that if the catalogue were ever momentarily empty — precisely what
   happens while an async fetch is in flight — every entry looked unknown, the
   bag was emptied, and the next save wrote that empty bag over the customer's
   inquiry. Persistence and validation are separate concerns: an entry is kept
   until the visitor removes it. */
function loadBag() {
  try {
    var raw = localStorage.getItem(BAG_KEY);
    var saved = raw ? JSON.parse(raw) : [];
    if (!Array.isArray(saved)) return;
    state.bag = saved
      .filter(function (b) { return b && b.id; })
      .map(function (b) { return { id: b.id, size: b.size }; });
  } catch (e) { state.bag = []; }
}

/* A saved entry whose product is not in the catalogue is still shown and still
   removable — it is never dropped on the visitor's behalf. Which message it
   carries depends on whether the catalogue has finished loading. */
function bagRowHTML(b, i) {
  var p = findBagProduct(b.id);
  var name = p ? p.name
    : catalogue.status === 'ready' ? 'No longer available'
    : catalogue.status === 'error' ? 'Couldn’t load this piece'
    : 'Loading…';
  /* Both halves are optional: the price is unknown until the catalogue lands,
     and the size is genuinely absent for a piece that publishes none. Built
     from whatever is actually known rather than from a fixed template with
     holes in it. */
  var bits = [];
  if (p && !blank(p.price)) bits.push(esc(p.price));
  if (!blank(b.size)) bits.push('Size ' + esc(b.size));
  var line = bits.join(' · ');

  return '<div class="bagrow"><div class="thumb">' +
    (p ? imgHTML(p.images[0], '92px', 'loading="lazy" decoding="async"') : '') + '</div>' +
    '<div class="info"><p class="name">' + esc(name) + '</p>' +
    (line ? '<p class="price">' + line + '</p>' : '') +
    '<p class="status" style="margin-top:2px">' + esc(p ? p.availabilityLabel : '') + '</p></div>' +
    '<button class="remove" data-remove="' + i + '" aria-label="Remove ' + esc(name) + ' from your inquiry">Remove</button></div>';
}

function renderBag() {
  byId('bag-count').textContent = String(state.bag.length);
  var n = state.bag.length;
  byId('bag-label').textContent = n === 0 ? 'Nothing selected yet'
    : n + (n === 1 ? ' look selected' : ' looks selected');

  byId('bag-list').innerHTML = n === 0
    ? '<div class="empty"><p class="body">You haven\'t selected any looks yet.</p>' +
      '<button class="pill pill-ghost" style="padding:14px 28px" data-nav="#/collection">Browse the collection</button></div>'
    : state.bag.map(function (b, i) { return bagRowHTML(b, i); }).join('');

  var submit = byId('inq-submit');
  submit.dataset.ready = String(n > 0);
  /* Never re-enable mid-flight: renderBag runs for reasons unrelated to the
     submission, and an enabled button during a request invites a second one. */
  submit.disabled = n === 0 || submitting;
}

/* Everything the atelier needs to answer an inquiry, in the shape
   POST /api/inquiries expects.

   Deliberately thin: product ids and the requested size, nothing else. Name,
   sku, slug and price are re-read from the database server-side, because a
   payload that has been sitting in a browser tab — or edited by hand — is a
   request, not a source of truth. The id identifies the piece; everything
   descriptive is the server's to decide. */
function inquiryPayload(form) {
  return {
    client_submission_id: submissionId(),
    customer: {
      name: form.name.value.trim(),
      phone: form.phone.value.trim(),
      email: form.email.value.trim(),
      note: form.note.value.trim()
    },
    items: state.bag.map(function (b) {
      var p = findBagProduct(b.id);
      return {
        product_id: p ? p.id : b.id,
        /* Normally null — the size selector is hidden. A bag saved before that
           still carries one, and it travels as written. */
        requested_size: blank(b.size) ? null : String(b.size)
      };
    })
  };
}

/* ---------- inquiry submission ---------- */

/* One id per submission *attempt*, held across retries on purpose. If the
   network drops after the server has committed, the customer's retry carries
   the same id, the unique constraint catches it, and they get the original
   inquiry back instead of a second one landing in Saima's inbox. Cleared only
   once a submission has actually succeeded. */
var SUBMISSION_KEY = 'meraki.inquiry.submission';
var currentSubmissionId = null;

function uuidv4() {
  if (window.crypto && crypto.randomUUID) return crypto.randomUUID();
  /* Older Safari. getRandomValues is available far earlier than randomUUID. */
  var b = new Uint8Array(16);
  (window.crypto || {}).getRandomValues
    ? crypto.getRandomValues(b)
    : (function () { for (var i = 0; i < 16; i++) b[i] = Math.floor(Math.random() * 256); })();
  b[6] = (b[6] & 0x0f) | 0x40;
  b[8] = (b[8] & 0x3f) | 0x80;
  var h = [];
  for (var i = 0; i < 16; i++) h.push((b[i] + 0x100).toString(16).slice(1));
  return h.slice(0, 4).join('') + '-' + h.slice(4, 6).join('') + '-' + h.slice(6, 8).join('') +
    '-' + h.slice(8, 10).join('') + '-' + h.slice(10, 16).join('');
}

function submissionId() {
  if (!currentSubmissionId) {
    /* Survives a reload mid-retry, so a customer who refreshes after a timeout
       still deduplicates against the attempt that may have landed. */
    try { currentSubmissionId = localStorage.getItem(SUBMISSION_KEY) || null; } catch (e) {}
    if (!currentSubmissionId) {
      currentSubmissionId = uuidv4();
      try { localStorage.setItem(SUBMISSION_KEY, currentSubmissionId); } catch (e) {}
    }
  }
  return currentSubmissionId;
}

function retireSubmissionId() {
  currentSubmissionId = null;
  try { localStorage.removeItem(SUBMISSION_KEY); } catch (e) {}
}

/* ---------- validation ---------- */

/* US only for now. The customer types whatever shape feels natural and it is
   reduced to one canonical form here; the same rule runs again server-side,
   which is the one that counts. Returns '+1XXXXXXXXXX' or null. */
function normalizeUsPhone(raw) {
  if (blank(raw)) return null;
  var s = String(raw).trim();
  if (s.length > 40) return null;
  if (/[a-z]/i.test(s)) return null;              /* letters, extensions */
  if (/[^0-9+()\-.\s]/.test(s)) return null;
  var digits = s.replace(/\D/g, '');
  if (digits.length === 11 && digits.charAt(0) === '1') digits = digits.slice(1);
  if (digits.length !== 10) return null;
  if (/^[01]/.test(digits) || /^[01]/.test(digits.slice(3))) return null;
  return '+1' + digits;
}

var EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

function setFieldError(name, message) {
  var el = byId('err-' + name);
  var input = $('#inquiry-form [name="' + name + '"]');
  if (el) {
    el.textContent = message || '';
    el.classList.toggle('hidden', !message);
  }
  if (input) {
    /* Not colour alone: the message is real text beside the field, and the
       state is announced. */
    if (message) input.setAttribute('aria-invalid', 'true');
    else input.removeAttribute('aria-invalid');
  }
}

function clearFieldErrors() {
  ['name', 'phone', 'email', 'note'].forEach(function (n) { setFieldError(n, ''); });
  var box = byId('inq-error');
  if (box) { box.textContent = ''; box.classList.add('hidden'); }
}

/* Returns the first invalid field name, or null. Messages say what to do rather
   than what went wrong. */
function validateInquiryForm(form) {
  clearFieldErrors();
  var first = null;
  var fail = function (n, m) { setFieldError(n, m); if (!first) first = n; };

  if (blank(form.name.value)) fail('name', 'Please tell us your name.');

  if (blank(form.phone.value)) fail('phone', 'Please add a phone number so we can reach you.');
  else if (!normalizeUsPhone(form.phone.value)) fail('phone', 'Enter a valid 10-digit U.S. phone number.');

  if (!blank(form.email.value) && !EMAIL_RE.test(form.email.value.trim().toLowerCase())) {
    fail('email', 'This email address doesn\'t look right.');
  }

  if (form.note.value.length > 2000) fail('note', 'Please keep this under 2000 characters.');

  return first;
}

function focusField(name) {
  var input = $('#inquiry-form [name="' + name + '"]');
  if (!input) return;
  try { input.focus({ preventScroll: true }); } catch (e) { input.focus(); }
  if (input.scrollIntoView) input.scrollIntoView({ block: 'center', behavior: 'smooth' });
}

function setSubmitting(on) {
  var btn = byId('inq-submit');
  if (!btn) return;
  btn.disabled = on || state.bag.length === 0;
  btn.dataset.sending = String(on);
  btn.textContent = on ? 'Sending…' : 'Request these looks';
}

function showFormError(message) {
  var box = byId('inq-error');
  if (!box) return;
  box.textContent = message;
  box.classList.remove('hidden');
}

/* ---------- image viewer ---------- */

/* Opening a photograph is for looking at the embroidery, so the viewer loads
   the master rather than a rendition — image.src is the master, and no srcset
   is set here on purpose. The responsive selection on the page itself is
   untouched; this is a separate, deliberate request for the largest source.

   Only PDP gallery images open it. A catalogue card is a link to a product and
   stays one. */
var lightbox = { open: false, shots: [], index: 0, returnFocus: null, scrollY: 0 };

function lbEl(id) { return byId(id); }

/* iOS ignores `overflow:hidden` on body often enough to be unreliable, so the
   page is pinned by position and put back exactly where it was on close. */
function lockPageScroll() {
  lightbox.scrollY = window.scrollY || window.pageYOffset || 0;
  document.body.style.position = 'fixed';
  document.body.style.top = -lightbox.scrollY + 'px';
  document.body.style.left = '0';
  document.body.style.right = '0';
  document.body.style.width = '100%';
}

function unlockPageScroll() {
  document.body.style.position = '';
  document.body.style.top = '';
  document.body.style.left = '';
  document.body.style.right = '';
  document.body.style.width = '';
  /* The stylesheet sets scroll-behavior:smooth, which makes this restore an
     animation that races the layout coming back — the page lands somewhere
     short of where it started. Putting someone back where they were is not a
     journey, so it is done instantly and the preference is put back. */
  var root = document.documentElement;
  var prior = root.style.scrollBehavior;
  root.style.scrollBehavior = 'auto';
  /* Two goes on purpose. Un-fixing the body does not restore the document's
     full height synchronously, so the first scroll can still be clamped
     against the collapsed page; the second runs once layout has settled and
     lands exactly. Reading scrollHeight forces the reflow in between. */
  var y = lightbox.scrollY;
  void root.scrollHeight;
  window.scrollTo(0, y);
  requestAnimationFrame(function () {
    window.scrollTo(0, y);
    root.style.scrollBehavior = prior;
  });
}

function renderLightbox() {
  var shot = lightbox.shots[lightbox.index];
  if (!shot) return;
  var img = lbEl('lb-img');
  /* The master, at full size. No srcset: a rendition is the wrong answer to
     "let me look closely". */
  img.removeAttribute('srcset');
  img.removeAttribute('sizes');
  img.src = shot.src;
  img.alt = shot.alt || '';

  var many = lightbox.shots.length > 1;
  lbEl('lb-prev').classList.toggle('hidden', !many);
  lbEl('lb-next').classList.toggle('hidden', !many);
  lbEl('lb-count').textContent = many ? (lightbox.index + 1) + ' / ' + lightbox.shots.length : '';
}

function openLightbox(shots, index, trigger) {
  if (!shots || !shots.length) return;
  lightbox.shots = shots;
  lightbox.index = Math.max(0, Math.min(index || 0, shots.length - 1));
  lightbox.returnFocus = trigger || null;
  lightbox.open = true;

  lockPageScroll();
  byId('lightbox').classList.remove('hidden');
  renderLightbox();
  /* Focus lands on Close so the first key press does the obvious thing, and so
     focus is never left sitting behind the overlay. */
  lbEl('lb-close').focus();
}

function closeLightbox() {
  if (!lightbox.open) return;
  lightbox.open = false;
  byId('lightbox').classList.add('hidden');
  /* Release the master so a long browse does not hold every photograph open. */
  lbEl('lb-img').removeAttribute('src');
  unlockPageScroll();
  if (lightbox.returnFocus && lightbox.returnFocus.focus) lightbox.returnFocus.focus();
  lightbox.returnFocus = null;
}

function stepLightbox(delta) {
  if (!lightbox.open || lightbox.shots.length < 2) return;
  var n = lightbox.shots.length;
  lightbox.index = (lightbox.index + delta + n) % n;   /* wraps both ways */
  renderLightbox();
}

/* The photographs of the piece currently on screen. */
function currentGalleryShots() {
  var p = findProductBySlug(state.slug);
  return p ? p.images : [];
}

/* The main photograph carries button semantics in the markup, so it also has
   to answer to the keys a button answers to. */
byId('pdp-hero').addEventListener('keydown', function (e) {
  if (e.key !== 'Enter' && e.key !== ' ' && e.key !== 'Spacebar') return;
  e.preventDefault();
  openLightbox(currentGalleryShots(), state.shot, byId('pdp-hero'));
});

byId('lb-close').addEventListener('click', closeLightbox);
byId('lb-prev').addEventListener('click', function () { stepLightbox(-1); });
byId('lb-next').addEventListener('click', function () { stepLightbox(1); });

/* Backdrop closes; the photograph itself does not, so an attempt to pinch or
   pan cannot dismiss it by accident. */
byId('lightbox').addEventListener('click', function (e) {
  if (e.target === this || e.target === byId('lb-stage')) closeLightbox();
});

document.addEventListener('keydown', function (e) {
  if (!lightbox.open) return;
  if (e.key === 'Escape') { closeLightbox(); return; }
  if (e.key === 'ArrowLeft') { stepLightbox(-1); return; }
  if (e.key === 'ArrowRight') { stepLightbox(1); }
});

/* Swipe between photographs. Deliberately crude: one axis, one threshold, and
   it defers to a vertical gesture so panning a zoomed image still works. */
var touchStart = null;
byId('lb-stage').addEventListener('touchstart', function (e) {
  if (e.touches.length !== 1) { touchStart = null; return; }   /* a pinch, leave it alone */
  touchStart = { x: e.touches[0].clientX, y: e.touches[0].clientY };
}, { passive: true });

byId('lb-stage').addEventListener('touchend', function (e) {
  if (!touchStart || !e.changedTouches.length) return;
  var dx = e.changedTouches[0].clientX - touchStart.x;
  var dy = e.changedTouches[0].clientY - touchStart.y;
  touchStart = null;
  if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) stepLightbox(dx < 0 ? 1 : -1);
}, { passive: true });

/* ---------- routing ---------- */
var VIEWS = ['home', 'collection', 'product', 'inquiry'];

function show(view) {
  VIEWS.forEach(function (v) { byId('view-' + v).classList.toggle('hidden', v !== view); });
}

function route() {
  var hash = location.hash.replace(/^#\/?/, '');

  /* Leaving the inquiry page retires the thank-you screen, so the next visit
     starts a fresh inquiry rather than showing the old confirmation forever. */
  if (hash !== 'inquiry') state.sent = false;

  if (hash.indexOf('product/') === 0) {
    state.slug = decodeURIComponent(hash.slice(8));
    state.size = null; state.shot = 0;
    renderProduct(); show('product'); window.scrollTo(0, 0); return;
  }
  if (hash === 'collection' || hash === 'ready' || hash === 'made-to-order') {
    state.filter = hash === 'ready' ? 'ready' : (hash === 'made-to-order' ? 'mto' : 'all');
    renderGrids(); show('collection'); window.scrollTo(0, 0); return;
  }
  if (hash === 'inquiry') {
    byId('inq-form-wrap').classList.toggle('hidden', state.sent);
    byId('inq-thanks').classList.toggle('hidden', !state.sent);
    renderBag(); show('inquiry'); window.scrollTo(0, 0); return;
  }

  show('home');
  if (hash === 'story') {
    var el = byId('story');
    if (el) window.scrollTo({ top: el.offsetTop - 90, behavior: 'smooth' });
  } else {
    window.scrollTo(0, 0);
  }
}

/* ---------- events (delegated) ---------- */
document.addEventListener('click', function (e) {
  if (!e.target || !e.target.closest) return;

  var nav = e.target.closest('[data-nav]');
  if (nav) { location.hash = nav.dataset.nav; return; }

  /* A thumbnail does both: it becomes the main photograph, so closing the
     viewer leaves the page on the shot the visitor last looked at, and it
     opens the viewer at that same shot. */
  var shot = e.target.closest('[data-shot]');
  if (shot) {
    var i = Number(shot.dataset.shot);
    state.shot = i;
    renderProduct();
    openLightbox(currentGalleryShots(), i, shot);
    return;
  }

  /* Only the PDP gallery opens the viewer. A catalogue card is a link to a
     product and stays one — it is not caught here at all. */
  if (e.target.id === 'pdp-hero') {
    openLightbox(currentGalleryShots(), state.shot, byId('pdp-hero'));
    return;
  }

  var size = e.target.closest('[data-size]');
  if (size) { state.size = size.dataset.size; renderProduct(); return; }

  var filt = e.target.closest('[data-filter]');
  if (filt) { state.filter = filt.dataset.filter; renderGrids(); return; }

  var rm = e.target.closest('[data-remove]');
  if (rm) { state.bag.splice(Number(rm.dataset.remove), 1); saveBag(); renderBag(); return; }

  if (e.target.closest('#pdp-add')) {
    var p = findProductBySlug(state.slug);
    if (!p || state.bag.some(function (b) { return b.id === p.id; })) return;
    /* A size is required only when one was actually offered. */
    var offered = SHOW_SIZE_SELECTION && p.sizes.length > 0;
    if (offered && !state.size) return;
    state.bag.push({ id: p.id, size: offered ? state.size : null });   /* identity is the id, never the slug */
    saveBag(); renderProduct(); renderBag();
  }
});

var INQUIRIES_ENDPOINT = '/api/inquiries';

/* The bag is cleared and the thank-you shown only after the server has
   confirmed. A failure leaves everything exactly as the customer left it —
   their looks, their typed answers — so retrying costs them nothing. */
byId('inquiry-form').addEventListener('submit', function (e) {
  e.preventDefault();
  var form = e.target;

  if (submitting || !state.bag.length) return;

  var invalid = validateInquiryForm(form);
  if (invalid) { focusField(invalid); return; }

  submitting = true;
  setSubmitting(true);

  var payload = inquiryPayload(form);

  fetch(INQUIRIES_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
    body: JSON.stringify(payload)
  })
    .then(function (res) {
      return res.json().catch(function () { return null; }).then(function (data) {
        return { status: res.status, ok: res.ok, data: data };
      });
    })
    .then(function (r) {
      if (!r.ok || !r.data || r.data.ok !== true) throw r;

      /* Committed. Only now is anything thrown away — and the submission id is
         retired so the next inquiry starts a new one. */
      retireSubmissionId();
      state.sent = true;
      state.bag = [];
      saveBag();
      form.reset();
      clearFieldErrors();
      renderBag();
      route();
    })
    .catch(function (r) {
      /* The bag survives, the form keeps its values, and the same submission id
         is reused on the next attempt. */
      var code = r && r.data && r.data.error;
      showFormError(
        code === 'invalid_phone' ? 'Enter a valid 10-digit U.S. phone number.'
        : code === 'invalid_email' ? 'This email address doesn\'t look right.'
        : code === 'name_required' ? 'Please tell us your name.'
        : code === 'product_unavailable' ? 'One of these pieces is no longer available. Please remove it and try again.'
        : code === 'too_many_requests' ? 'That was a lot of tries at once. Please wait a moment and send again.'
        : 'We couldn\'t send your inquiry just now. Please try again in a moment.');
      if (code === 'invalid_phone') { setFieldError('phone', 'Enter a valid 10-digit U.S. phone number.'); focusField('phone'); }
      if (code === 'invalid_email') { setFieldError('email', 'This email address doesn\'t look right.'); focusField('email'); }
    })
    .then(function () {
      submitting = false;
      setSubmitting(false);
    });
});

/* Validate on the way out of a field rather than on every keystroke: nobody
   wants to be told their phone number is wrong while they are still typing it. */
['name', 'phone', 'email'].forEach(function (name) {
  var input = $('#inquiry-form [name="' + name + '"]');
  if (!input) return;
  input.addEventListener('blur', function () {
    if (blank(input.value)) { if (name !== 'email') setFieldError(name, ''); return; }
    if (name === 'phone' && !normalizeUsPhone(input.value)) {
      setFieldError('phone', 'Enter a valid 10-digit U.S. phone number.');
    } else if (name === 'email' && !EMAIL_RE.test(input.value.trim().toLowerCase())) {
      setFieldError('email', 'This email address doesn\'t look right.');
    } else {
      setFieldError(name, '');
    }
  });
});

/* Fetch the published catalogue and hand every product through the same
   mapProduct() the fixtures went through. There is deliberately no embedded
   fallback catalogue: if this fails the storefront says so, rather than
   quietly serving a copy of the products baked in at deploy time. */
function loadCatalogue() {
  setCatalogueState('loading');

  return fetch(PRODUCTS_ENDPOINT, { headers: { Accept: 'application/json' } })
    .then(function (res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.json();
    })
    .then(function (payload) {
      var mapped = mapProducts(payload && payload.products);
      PRODUCTS.length = 0;
      PRODUCTS.push.apply(PRODUCTS, mapped);
      setCatalogueState('ready');
    })
    .catch(function (err) {
      PRODUCTS.length = 0;
      setCatalogueState('error', err);
    });
}

/* ---------- website settings ---------- */

/* Fill an element with text, or hide it. Every settings-driven line on the page
   goes through here, so "Saima has not filled this in" always renders the same
   way: the line is absent, never an empty label, a dangling separator or a
   placeholder standing in for a real answer. The prefix is the punctuation that
   only makes sense once there is something to punctuate. */
function setSettingLine(id, value, prefix) {
  var el = byId(id);
  if (!el) return null;
  var empty = blank(value);
  el.textContent = empty ? '' : (prefix || '') + String(value).trim();
  el.classList.toggle('hidden', empty);
  return empty ? null : el;
}

/* The app stores WhatsApp as international digits and renders it as "+digits".
   wa.me wants the digits alone, so anything a human may have typed around them
   — plus, spaces, brackets, dashes — is stripped here rather than assumed
   absent. No digits means no link: a bare https://wa.me/ is a broken promise,
   not a contact detail. */
function whatsappHref(value) {
  var digits = blank(value) ? '' : String(value).replace(/\D+/g, '');
  return digits ? 'https://wa.me/' + digits : null;
}

/* Saved as a full profile URL by the app, but a bare handle or a scheme-less
   host would both otherwise resolve as a relative path on this site. */
function externalHref(value) {
  if (blank(value)) return null;
  var url = String(value).trim();
  return /^https?:\/\//i.test(url) ? url : 'https://' + url.replace(/^\/+/, '');
}

function setContactLink(id, href, label) {
  var el = byId(id);
  if (!el) return false;
  if (!href) {
    el.classList.add('hidden');
    el.removeAttribute('href');
    return false;
  }
  el.href = href;
  if (label) el.textContent = label;
  el.classList.remove('hidden');
  return true;
}

/* Everything Saima maintains in the app, written onto the page in one place.
   Called once at load with blank settings and again when the fetch resolves,
   so it has to be idempotent in both directions — each branch sets *and*
   clears, and none of them leaves a stale value behind on failure. */
function applySettings() {
  var s = SETTINGS;

  /* Reads "…cut, embroidered and shipped in 4–6 weeks", or just "…and shipped"
     when no lead time is published. */
  setSettingLine('step-lead-time', s.made_to_order_lead_time, ' in ');
  setSettingLine('footer-lead-time', s.made_to_order_lead_time, ' · ');
  setSettingLine('footer-size-note', sizeServiceNote());
  setSettingLine('footer-location', s.location);
  setSettingLine('pdp-size-note', sizeServiceNote());
  setSettingLine('inq-response-note', s.inquiry_response_note);

  var contacts = [
    setContactLink('contact-whatsapp', whatsappHref(s.whatsapp), 'WhatsApp'),
    setContactLink('contact-email', blank(s.contact_email) ? null : 'mailto:' + s.contact_email, s.contact_email),
    setContactLink('contact-instagram', externalHref(s.instagram_url), 'Instagram')
  ].filter(Boolean).length;

  /* A "Contact" heading with nothing under it reads as a broken page rather
     than an unfilled setting, so the column goes with its last link. */
  var col = byId('footer-contact');
  if (col) col.classList.toggle('hidden', contacts === 0);
}

/* Settings are not load-bearing: the catalogue is the storefront, and a
   settings outage must cost a few optional lines rather than the shop. So the
   failure path is blank settings, not an error state, and the promise always
   resolves. */
function loadSettings() {
  return fetch(SETTINGS_ENDPOINT, { headers: { Accept: 'application/json' } })
    .then(function (res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.json();
    })
    .then(function (payload) {
      var incoming = (payload && payload.settings) || {};
      var next = blankSettings();
      Object.keys(next).forEach(function (k) {
        next[k] = blank(incoming[k]) ? null : String(incoming[k]).trim();
      });
      SETTINGS = next;
    })
    .catch(function (err) {
      SETTINGS = blankSettings();
      if (window.console && console.warn) console.warn('Site settings unavailable:', err);
    })
    .then(function () {
      applySettings();
      refreshViews();
    });
}

/* Re-render what is already on screen without re-running the route. The
   catalogue and the settings arrive independently and either can land after
   the visitor has started reading; routing again here would scroll them back
   to the top of the page mid-sentence. */
function refreshViews() {
  renderGrids();
  if (state.slug) renderProduct();
  renderBag();
}

/* Nobody should have to redeploy the site in January. */
function renderCopyrightYear() {
  var el = byId('copyright-year');
  if (el) el.textContent = String(new Date().getFullYear());
}

/* A candidate chosen from srcset that fails to load does NOT make the browser
   fall back to src — the element just goes broken. Every image here has a valid
   master in src, so one retry without srcset is the difference between a
   question mark and the photograph.
 *
 * Retried once and only once, and nothing is swallowed: if the master fails too
 * the image stays visibly broken, which is a real failure worth seeing. Error
 * events do not bubble, so this listens in the capture phase. */
document.addEventListener('error', function (e) {
  var img = e.target;
  if (!img || img.tagName !== 'IMG') return;
  if (!img.getAttribute('srcset') || img.dataset.srcsetRetried) return;
  img.dataset.srcsetRetried = '1';
  if (window.console && console.warn) {
    console.warn('Image candidate failed; falling back to the master:', img.currentSrc || img.src);
  }
  img.removeAttribute('srcset');
  img.removeAttribute('sizes');
  /* Reassigning src is what restarts the load now that the candidate list is
     gone; without it the element keeps its failed state. */
  var src = img.getAttribute('src');
  if (src) img.src = src;
}, true);

window.addEventListener('hashchange', route);
renderCopyrightYear();
applySettings();   /* blank until the fetch lands: hides every line it cannot fill */
loadBag();
loadCatalogue();
loadSettings();
