#!/usr/bin/env python3
"""Regenerate the web-optimised images in img/ from the originals in img/source/.

Run this after dropping a new photograph into img/source/:

    python3 tools/optimize-images.py

Requires Pillow (`pip install Pillow`). It never crops, rotates, recolours or
otherwise alters a photograph — it only resizes proportionally and re-encodes.

For every img/source/<name>.<ext> it writes:
    img/<name>.webp      full-size, capped at MAX_W  — used by the hero and the
                         product page
    img/md/<name>.webp   capped at MED_W             — used by cards on phones
    img/sm/<name>.webp   capped at SMALL_W           — used by the card grid on
                         desktop, the gallery thumbnails and the inquiry rows

The logo is handled separately: it is only ever drawn ~54px tall, so it is
capped at LOGO_H and keeps its alpha channel.
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required:  pip install Pillow")

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "img" / "source"
IMG = ROOT / "img"
SM = IMG / "sm"
MD = IMG / "md"

MAX_W = 1400      # enough for a 2x hero on a 1440px-wide desktop
MED_W = 960       # enough for a 2x product card on a phone
SMALL_W = 560     # enough for a 2x product card on desktop (~280px wide)
QUALITY = 80
MED_QUALITY = 79
SMALL_QUALITY = 78
LOGO_H = 220      # the logo is never drawn taller than ~54px
LOGO_QUALITY = 90
OG_SOURCE = "p5"  # the hero photograph, reused for link previews


def resize(im, max_w=None, max_h=None):
    w, h = im.size
    scale = 1.0
    if max_w:
        scale = min(scale, max_w / w)
    if max_h:
        scale = min(scale, max_h / h)
    if scale >= 1.0:
        return im
    return im.resize((round(w * scale), round(h * scale)), Image.LANCZOS)


def kb(path):
    return path.stat().st_size / 1024


def write_manifest(photos):
    """Rewrite the generated IMG_SRCSET block in script.js.

    Each entry maps the full-size path to a ready-made srcset string using the
    real pixel widths on disk, so the browser can pick the cheapest rendition
    that still looks sharp. A photograph that is missing from this block simply
    renders from its `src` with no srcset — nothing breaks.
    """
    lines = []
    for src in photos:
        full = IMG / f"{src.stem}.webp"
        if not full.exists():
            continue
        seen, cands = set(), []
        for path in (SM / f"{src.stem}.webp", MD / f"{src.stem}.webp", full):
            if not path.exists():
                continue
            with Image.open(path) as im:
                w = im.size[0]
            if w in seen:
                continue
            seen.add(w)
            cands.append(f"{path.relative_to(ROOT).as_posix()} {w}w")
        lines.append(f"  '{full.relative_to(ROOT).as_posix()}': '{', '.join(cands)}'")

    block = ("/* IMG-SRCSET:START — generated by tools/optimize-images.py, do not edit by hand */\n"
             "var IMG_SRCSET = {\n" + ",\n".join(lines) + "\n};\n"
             "/* IMG-SRCSET:END */")

    js = ROOT / "script.js"
    text = js.read_text()
    start, end = text.find("/* IMG-SRCSET:START"), text.find("/* IMG-SRCSET:END */")
    if start == -1 or end == -1:
        print("! script.js has no IMG-SRCSET block — skipping manifest")
        return
    end += len("/* IMG-SRCSET:END */")
    js.write_text(text[:start] + block + text[end:])
    print(f"\nwrote srcset manifest for {len(lines)} photographs into script.js")


def make_og_image():
    """A JPEG copy of the hero photograph for link previews.

    Uncropped and unaltered — only scaled down. Social platforms prefer JPEG or
    PNG over WebP, hence the separate file.
    """
    hero = SRC / f"{OG_SOURCE}.webp"
    if not hero.exists():
        return
    with Image.open(hero) as im:
        out = resize(im.convert("RGB"), max_w=1200)
        out.save(IMG / "og.jpg", "JPEG", quality=82, optimize=True, progressive=True)
    print(f"og.jpg        {out.size[0]}x{out.size[1]} {kb(IMG / 'og.jpg'):.0f}kB "
          f"(copy of {OG_SOURCE}, uncropped)")


def main():
    if not SRC.is_dir():
        sys.exit(f"no source directory: {SRC}")
    SM.mkdir(parents=True, exist_ok=True)
    MD.mkdir(parents=True, exist_ok=True)

    photos = sorted(p for p in SRC.iterdir()
                    if p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".tif", ".tiff"}
                    and p.stem != "logo")

    total_before = total_after = 0.0

    for src in photos:
        with Image.open(src) as im:
            im = im.convert("RGB")
            full = resize(im, max_w=MAX_W)
            out = IMG / f"{src.stem}.webp"
            full.save(out, "WEBP", quality=QUALITY, method=6)

            # Only worth a separate rendition if it is genuinely narrower than
            # the full-size file — otherwise it would be a near-identical copy.
            out_md = MD / f"{src.stem}.webp"
            if MED_W < full.size[0]:
                resize(im, max_w=MED_W).save(out_md, "WEBP", quality=MED_QUALITY, method=6)
            elif out_md.exists():
                out_md.unlink()

            small = resize(im, max_w=SMALL_W)
            out_sm = SM / f"{src.stem}.webp"
            small.save(out_sm, "WEBP", quality=SMALL_QUALITY, method=6)

        md_kb = kb(out_md) if out_md.exists() else 0
        before, after = kb(src), kb(out) + md_kb + kb(out_sm)
        total_before += before
        total_after += after
        print(f"{src.name:14s} {im.size[0]}x{im.size[1]} {before:8.0f}kB"
              f"  ->  {full.size[0]}x{full.size[1]} {kb(out):6.0f}kB"
              f"  + md {md_kb:5.0f}kB + sm {kb(out_sm):5.0f}kB")

    write_manifest(photos)
    make_og_image()

    logo_src = next((SRC / f"logo{e}" for e in (".png", ".webp", ".jpg")
                     if (SRC / f"logo{e}").exists()), None)
    if logo_src:
        with Image.open(logo_src) as im:
            im = im.convert("RGBA")
            logo = resize(im, max_h=LOGO_H)
            out = IMG / "logo.png"
            logo.save(out, "PNG", optimize=True)
            # small square mark for the browser tab / home screen
            icon = resize(im, max_w=180, max_h=180)
            canvas = Image.new("RGBA", (180, 180), (0, 0, 0, 0))
            canvas.paste(icon, ((180 - icon.width) // 2, (180 - icon.height) // 2), icon)
            canvas.save(IMG / "icon.png", "PNG", optimize=True)
        before, after = kb(logo_src), kb(out) + kb(IMG / "icon.png")
        total_before += before
        total_after += after
        print(f"{logo_src.name:14s} {im.size[0]}x{im.size[1]} {before:8.0f}kB"
              f"  ->  {logo.size[0]}x{logo.size[1]} {kb(out):6.0f}kB"
              f"  + icon 180x180 {kb(IMG / 'icon.png'):5.0f}kB")

    print(f"\ntotal {total_before/1024:.2f} MB  ->  {total_after/1024:.2f} MB"
          f"  ({100 * (1 - total_after / total_before):.0f}% smaller)")


if __name__ == "__main__":
    main()
