-- Website inquiries — storefront-first schema.
--
-- Run this once in the Supabase SQL editor (see sql/README.md). The storefront's
-- POST /api/inquiries fails closed until it exists.
--
-- The admin app will read these tables in a later task. It normally owns the
-- migration history, so this file is written to be safe to re-run and safe to
-- fold into that history later: every statement is guarded, and nothing here
-- alters an existing table.

-- ---------------------------------------------------------------- inquiries
create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- One submission attempt, generated by the browser. Unique, so a retry after
  -- a network timeout resolves to the inquiry that was already created rather
  -- than a second one.
  client_submission_id uuid not null unique,

  source text not null default 'website',

  customer_name text not null,
  phone text not null,            -- canonical +1XXXXXXXXXX, normalised server-side
  email text,
  note text,

  status text not null default 'new'
);

-- Guarded so re-running cannot fail on an existing constraint.
do $$ begin
  alter table public.inquiries
    add constraint inquiries_status_check check (status in ('new', 'contacted', 'closed'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.inquiries
    add constraint inquiries_customer_name_not_blank check (btrim(customer_name) <> '');
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.inquiries
    add constraint inquiries_phone_e164_us check (phone ~ '^\+1[0-9]{10}$');
exception when duplicate_object then null; end $$;

create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);
create index if not exists inquiries_status_idx on public.inquiries (status);

-- ----------------------------------------------------------- inquiry_items
-- The snapshot columns are deliberate: an inquiry has to stay readable a year
-- from now even if the piece has been renamed, repriced, unpublished, archived
-- or deleted. product_id keeps the live link where one still exists.
create table if not exists public.inquiry_items (
  id uuid primary key default gen_random_uuid(),
  inquiry_id uuid not null references public.inquiries (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,

  product_slug text,
  product_sku text,
  product_name text,

  requested_size text,            -- normally null: the size selector is hidden
  price_snapshot numeric,

  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists inquiry_items_inquiry_id_idx on public.inquiry_items (inquiry_id);
create index if not exists inquiry_items_product_id_idx on public.inquiry_items (product_id);

-- ------------------------------------------------------------ updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists inquiries_set_updated_at on public.inquiries;
create trigger inquiries_set_updated_at
  before update on public.inquiries
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------- RLS
-- Both tables are service-role only. The browser never talks to PostgREST for
-- these — it posts to /api/inquiries, which holds the key server-side. Enabling
-- RLS with no policy denies anon and authenticated outright; the service role
-- bypasses RLS, so the endpoint keeps working.
alter table public.inquiries enable row level security;
alter table public.inquiry_items enable row level security;

revoke all on public.inquiries from anon, authenticated;
revoke all on public.inquiry_items from anon, authenticated;

-- --------------------------------------------------- atomic creation (RPC)
-- One statement from the endpoint's point of view, so an inquiry can never be
-- left with half its items. A function body is a single transaction: if any
-- item insert fails, the inquiry row goes with it.
--
-- Idempotent by construction. The insert takes the unique constraint on
-- client_submission_id as the arbiter, so two concurrent retries of the same
-- submission cannot both create a row — the loser finds the winner's id and
-- reports it as a duplicate without touching items.
--
-- p_items is a JSON array built entirely from canonical product rows the
-- endpoint has already re-read. Nothing a browser sent reaches this function
-- except the requested size and the ordering.
create or replace function public.create_website_inquiry(
  p_client_submission_id uuid,
  p_customer_name text,
  p_phone text,
  p_email text,
  p_note text,
  p_items jsonb
)
returns table (inquiry_id uuid, duplicate boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'inquiry must have at least one item' using errcode = '22023';
  end if;

  insert into public.inquiries (client_submission_id, source, customer_name, phone, email, note)
  values (p_client_submission_id, 'website', p_customer_name, p_phone, p_email, p_note)
  on conflict (client_submission_id) do nothing
  returning id into v_id;

  if v_id is null then
    -- Already submitted. Return the original, and insert nothing.
    select i.id into v_id
      from public.inquiries i
     where i.client_submission_id = p_client_submission_id;

    inquiry_id := v_id;
    duplicate := true;
    return next;
    return;
  end if;

  insert into public.inquiry_items (
    inquiry_id, product_id, product_slug, product_sku, product_name,
    requested_size, price_snapshot, sort_order)
  select
    v_id,
    nullif(item->>'product_id', '')::uuid,
    item->>'product_slug',
    item->>'product_sku',
    item->>'product_name',
    nullif(item->>'requested_size', ''),
    nullif(item->>'price_snapshot', '')::numeric,
    coalesce((item->>'sort_order')::int, 0)
  from jsonb_array_elements(p_items) as item;

  inquiry_id := v_id;
  duplicate := false;
  return next;
end $$;

-- The function is reachable only by the service role, same as the tables.
revoke all on function public.create_website_inquiry(uuid, text, text, text, text, jsonb) from public, anon, authenticated;
